plugins {
    id 'java'
    id 'java-library'
    id 'jacoco'
    id 'maven-publish'
    id "org.sonarqube" version "4.4.1.3373"
}

group = "eu.nonstatic"
version = "0.4.1"

repositories {
    maven {
        url = uri("https://raw.githubusercontent.com/slok/algs4-mvn-repo/master/")
    }
    mavenLocal()
    mavenCentral()
}

def lombokVersion = '1.18.46'

dependencies {
    annotationProcessor("org.projectlombok:lombok:$lombokVersion")
    implementation("edu.princeton.cs.introcs:algs4-package:1.0")
    api('eu.nonstatic:timecode:1.0.0')
    implementation('org.slf4j:slf4j-api:2.0.17')
    compileOnly("org.projectlombok:lombok:$lombokVersion")

    runtimeOnly("com.googlecode.soundlibs:mp3spi:1.9.5.4")
    runtimeOnly("com.googlecode.soundlibs:vorbisspi:1.0.3.3")

    testImplementation(platform('org.junit:junit-bom:6.1.0'))
    testImplementation('org.junit.jupiter:junit-jupiter')
    testRuntimeOnly('org.junit.platform:junit-platform-launcher')
}

configurations.implementation {
    exclude group: 'org.slf4j', module: 'slf4j-simple'
}


java {
    sourceCompatibility = JavaVersion.toVersion("17")
    targetCompatibility = JavaVersion.toVersion("17")
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.compilerArgs.add('-parameters')
}


// use JUnit 5 platform
test {
    testLogging.showStandardStreams = true
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        html.required = true
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }

    repositories {
        mavenLocal()
        maven {
            name = "GitHubPackages"
            url = "https://maven.pkg.github.com/nonstaticeu/audiolib"
            credentials {
                username = System.getenv("GITHUB_ACTOR")
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
}
